language: "node_js"
node_js:
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - "node_modules"
script:
  - npm run validate
  - npm run build
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: "patrick.d.hooper@gmail.com"
  api_key: "$NPM_AUTH_TOKEN"
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d.*$/
